# Generated by Django 4.2.13 on 2024-05-26 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='UploaFile',
        ),
    ]
