# Generated by Django 5.0.6 on 2024-05-16 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="content",
            field=models.TextField(default="message", max_length=1024),
        ),
    ]
