# Generated by Django 4.2.13 on 2024-05-26 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_file_uploafile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploaFile',
            new_name='UploadedFile',
        ),
    ]
